spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:file:./db}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
    dbcp2:
      validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
springdoc:
  pathsToMatch: /api/**
application:
  security:
    jwt:
      secret-key: 6352665584720B4B6250644E7235755367566B56A586E32438782F413F442970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
# logging:
#  level:
#    root: debug